import csv

def generate_signature(text, comment):
    variable_name = text.replace('/','').replace(' ','').replace('-','').upper()

    return f"FILING_{variable_name} = '{text}' # {comment}\n"
signatures = []
with open('tabula-edgarfm-vol2-v55.csv') as f:
    
    csv_reader = csv.reader(f)
    current_description_i = -1
    current_type_i = -1
    for row in csv_reader:
        row = [i.replace('\n',' ') for i in row]
        score = 0
        for i, field in enumerate(row):
            if field == 'Description':
                score += 1
                current_description_i = i
            elif field == 'Submission Type':
                current_type_i = i
                score += 1
        assert score != 1
        if score == 2:
            continue

        descr = row[current_description_i]
        types = [x.strip() for x in row[current_type_i].split(',')]
        signatures.extend(list(map(lambda x: generate_signature(x, descr), types)))

with open('out.py', 'w') as f:
    f.write('# Generated by gen_filing_type_enum.py as of 2/27/2021\n')
    for row in signatures:
        f.write(row)